baseurl                  = "/"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Észak Ösvényein"
theme                  = "sam"                      # install theme locally (git clone or submodule)
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
googleAnalyticsID        = "G-8KK4WVGQV2"                               # Tracking code, eg. "UA-111111111-1"
summaryLength = 5
disqusShortname = 'seseragisan'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "főoldal"                           # What to call the home page link, link will not be rendered if empty
    footerText           = ' _„...hogy zöldjeik kékbe játszó érzékeny árnyalataival természetesen közlik távolságukat...”_ -- Krasznahorkai László '

# Metadata for Open Graph and Twitter
    description          = "Észak Ösvényein"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Észak Ösvényein"
    # rss                = ""

#[[params.videoBackground.sources]]
#    source  = "/sample_video.mp4"
#    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "posts"
    text = "Észak ösvényein"

[[params.mainMenu]]
    link = "gallery"
    text = "Japán '17-18"

[[params.mainMenu]]
    link = "about"
    text = "Rólam"

[imaging]
    quality = 75
